version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: symfony
       MYSQL_DATABASE: library
       MYSQL_USER: symfony
       MYSQL_PASSWORD: symfony

   pma:
      image: dnhsoft/phpmyadmin
      ports:
       - "8003:80"
      links:
       - db:db
      environment:
        DBHOST: db
        DBUSER: symfony
        DBPASS: symfony

   symfony:
     depends_on:
       - db
     image: nimmis/apache-php5
     volumes:
       - "./symfony:/var/www/html"
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: symfony
       WORDPRESS_DB_PASSWORD: symfony
volumes:
    db_data: